spring:
  application:
    name: regist-consumer
  redis:
    host: 192.168.32.131
    port: 6379
    password:
    jedis:
      pool:
        max-active: 20

server:
  port: 7762

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

